### ISSUE TITLE
"JJGuns" cheat crashes JJ2 port.

### ISSUE THREAD

**Issue by NJW1979** [deathkiller/jazz2#56]
I was able to get god mode to work on the port but as soon as I enabled the JJGuns cheat the game froze and crashed without an error message.

**Comment by NJW1979** [comment]
This was also from Event Viewer:

Application: Jazz2.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IndexOutOfRangeException
   at Jazz2.Game.LevelHandler.ProcessCheats()
   at Jazz2.Game.LevelHandler.OnUpdate()
   at Jazz2.Game.LevelHandler+LocalController.Duality.ICmpUpdatable.OnUpdate()
   at Duality.Resources.Scene+<>c.<Update>b__69_0(Duality.ICmpUpdatable)
   at Duality.Resources.Scene.UpdateComponents[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Action`1<System.__Canon>)
   at Duality.Resources.Scene.Update()
   at Duality.DualityApp.Update()
   at Duality.Backend.GL21.NativeWindow.OnUpdateFrame(OpenTK.FrameEventArgs)
   at Duality.Backend.GL21.NativeWindow+InternalWindow.OnUpdateFrame(OpenTK.FrameEventArgs)
   at OpenTK.GameWindow.RaiseUpdateFrame(Double, Double ByRef)
   at OpenTK.GameWindow.DispatchUpdateAndRenderFrame(System.Object, System.EventArgs)
   at OpenTK.GameWindow.Run(Double, Double)
   at Duality.Backend.GL21.NativeWindow.Duality.Backend.INativeWindow.Run()
   at Jazz2.Game.App.Main(System.String[])

**Comment by deathkiller** [comment]
Closed due to inactivity.
